server:
  port: 8000

spring:
  application:
    name: registry-service

eureka:
  instance:
    hostname: "${HOST_NAME:localhost}.eureka"
  client:
    fetch-registry: off
    register-with-eureka: off
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8000/eureka}